{
 "title": "Beyla process metrics",
 "description": "Information about the processes belonging to the applications instrumented by Beyla",
 "tags": [
  "process",
  "beyla"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"process_cpu_time.*\",process_pid=\"\"}[$__interval]) + on(instance) group_left(k8s_pod_name,k8s_namespace_name,process_command,process_pid) (0 * target_info{process_pid!=\"\"})) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    },
    {
     "expr": "sum(rate({__name__=~\"process_cpu_time.*\",process_pid!=\"\"}[$__interval])) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"process_memory_usage.*\",process_pid=\"\"} + on(instance) group_left(k8s_pod_name,k8s_namespace_name,process_command,process_pid) (0 * target_info{process_pid!=\"\"})) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    },
    {
     "expr": "sum({__name__=~\"process_memory_usage.*\",process_pid!=\"\"}) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"process_memory_virtual.*\",process_pid=\"\"} + on(instance) group_left(k8s_pod_name,k8s_namespace_name,process_command,process_pid) (0 * target_info{process_pid!=\"\"})) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    },
    {
     "expr": "sum({__name__=~\"process_memory_virtual.*\",process_pid!=\"\"}) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    }
   ]
  },
  {
   "title": "Disk I/O read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"process_disk_io.*\",process_pid=\"\",disk_io_direction=\"read\"}[$__interval]) + on(instance) group_left(k8s_pod_name,k8s_namespace_name,process_command,process_pid) (0 * target_info{process_pid!=\"\"})) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    },
    {
     "expr": "sum(rate({__name__=~\"process_disk_io.*\",process_pid!=\"\",disk_io_direction=\"read\"}[$__interval])) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    }
   ]
  },
  {
   "title": "Disk I/O write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"process_disk_io.*\",process_pid=\"\",disk_io_direction=\"write\"}[$__interval]) + on(instance) group_left(k8s_pod_name,k8s_namespace_name,process_command,process_pid) (0 * target_info{process_pid!=\"\"})) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    },
    {
     "expr": "sum(rate({__name__=~\"process_disk_io.*\",process_pid!=\"\",disk_io_direction=\"write\"}[$__interval])) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    }
   ]
  },
  {
   "title": "Network I/O receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"process_network_io.*\",process_pid=\"\",network_io_direction=\"receive\"}[$__interval]) + on(instance) group_left(k8s_pod_name,k8s_namespace_name,process_command,process_pid) (0 * target_info{process_pid!=\"\"})) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    },
    {
     "expr": "sum(rate({__name__=~\"process_network_io.*\",process_pid!=\"\",network_io_direction=\"receive\"}[$__interval])) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    }
   ]
  },
  {
   "title": "Network I/O transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"process_network_io.*\",process_pid=\"\",network_io_direction=\"transmit\"}[$__interval]) + on(instance) group_left(k8s_pod_name,k8s_namespace_name,process_command,process_pid) (0 * target_info{process_pid!=\"\"})) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    },
    {
     "expr": "sum(rate({__name__=~\"process_network_io.*\",process_pid!=\"\",network_io_direction=\"transmit\"}[$__interval])) by(k8s_pod_name,k8s_namespace_name,process_command,process_pid)",
     "legendFormat": "{{process_command}}/{{process_pid}} (Pod: {{k8s_namespace_name}}/{{k8s_pod_name}})"
    }
   ]
  }
 ]
}